### ISSUE TITLE
Encryption is limited by size of state

### ISSUE THREAD

**Issue by MLFlexer** [MLFlexer/resurrect.wezterm#32]
This issue is related to the implementation of #1
> Do you easily reach the character limit, or do you have to have a lot of panes with a lot of out put in your experience?

PowerShell follows a Windows limit of 32,764 characters, so it takes a few tabs with a lot of text content in them to hit this limit. Since it's a Windows limit, I think the workaround would involve writing the saved state to a temporary file or compressing the command, but this adds quite a bit of code and complexity to the plugin that I'm hesitant to add.

Perhaps a better approach is to add some sample code to `encryption.md` for an `ecnrypt()` func that writes a temporary file, decrypts it with `age` and then deletes it, while flagging that this is less secure, but is an option.

_Originally posted by @joncrangle in https://github.com/MLFlexer/resurrect.wezterm/issues/31#issuecomment-2271286853_

**Comment by MLFlexer** [comment]
I see several "solutions" each with their own downsides:
1. A temp file could be used. This could lave the secrets in a temporary unencrypted state, thus being insecure.
2. Do not save the lines within the panes, this should drastically cut down on the number of chars, but will ofc be a worse user experience
3. Encrypt in chunks of 32,764 characters at a time. This will make the encryption and decryption logic a lot worse, but it will make it possible to keep the same security and functionality as the unix systems.
4. Do nothing by default and make it break at 32,764+ chars and then refeer to the encryption.md docs where we can suggest options for encrypting larger states

**Comment by joncrangle** [comment]
I've come across this issue on linux as well now, so I don't think it's Windows-specific - it's just that Windows supports the shortest character limits for commands compared to Unix-based systems.

in `pane_tree.lua`, the line 
```lua
root.text = root.pane:get_lines_as_escapes(root.pane:get_dimensions().scrollback_rows)
```
will return the entire scrollback history ([wezterm docs](https://wezfurlong.org/wezterm/config/lua/pane/get_lines_as_escapes.html?h=ansi)). I've got my scrollback set to 5,000 lines. Also, I use a colorful Starship prompt, and all those ansi color sequences add to the command length so I think that's why I've hit the limits a few times.

I wonder if a simpler way to address this issue is to allow the user to provide an optional `[nlines]` opt to specify the volume of lines they want to save. That way, the `pane_tree.lua` function can save the entire scrollback by default (as it is now) or the provided `nlines` if the user provides the `nlines` arg to override it.

> 1. A temp file could be used. This could lave the secrets in a temporary unencrypted state, thus being insecure.
> 2. Do not save the lines within the panes, this should drastically cut down on the number of chars, but will ofc be a worse user experience
> 3. Encrypt in chunks of 32,764 characters at a time. This will make the encryption and decryption logic a lot worse, but it will make it possible to keep the same security and functionality as the unix systems.

A benefit of the above approach to let the user optionally specify `nlines`, is that these options you suggested would still be available if someone wants to use their own encryption and decryption logic, but it wouldn't need to be maintained as part of the plugin.

**Comment by MLFlexer** [comment]
I really like the option of specifying the `nlines` even though it does not directly fix the underlying problem.

I might have a way to write to stdin via luas `popen`, but I will have to play around with it, as I havn't played a lot with lua i/o
