### ISSUE TITLE
add support for ExecDomain

### ISSUE THREAD

**Issue by MLFlexer** [MLFlexer/resurrect.wezterm#43]
[ExecDomains](https://wezfurlong.org/wezterm/config/lua/ExecDomain.html) should be supported

**Comment by joncrangle** [comment]
I found this comment by Wez helpful when I was researching domains https://github.com/wez/wezterm/discussions/4324#discussioncomment-7076398

I confess that I still don't fully grasp how domains work under the hood. I think that Exec domain is almost like the class instance for domain types. 

I plan to test connecting to a docker instance because I think it will use the UNIX domain.

**Comment by MLFlexer** [comment]
> I found this comment by Wez helpful when I was researching domains [wez/wezterm#4324 (comment)](https://github.com/wez/wezterm/discussions/4324#discussioncomment-7076398)
> 
> I confess that I still don't fully grasp how domains work under the hood. I think that Exec domain is almost like the class instance for domain types.
> 
> I plan to test connecting to a docker instance because I think it will use the UNIX domain.

Thanks for sharing!
