### ISSUE TITLE
Question: resurrect without spawning new window

### ISSUE THREAD

**Issue by weierophinney** [MLFlexer/resurrect.wezterm#67]
Using the configuration provided in the README.md, if I load a workspace saved with resurrect.wezterm, it currently spawns a new window. Is there a way to have it resurrect within the current window and replace any existing tabs and panes?

**Comment by MLFlexer** [comment]
There is a way to make it use your current window. If you supply the `load_state` function with a `opts` table containing the current window (Note I havn't tested the following code, but it should be possible):

```lua
 {
    key = "r",
    mods = "ALT",
    action = wezterm.action_callback(function(win, pane)
      resurrect.fuzzy_load(win, pane, function(id, label)
        local type = string.match(id, "^([^/]+)") -- match before '/'
        id = string.match(id, "([^/]+)$") -- match after '/'
        id = string.match(id, "(.+)%..+$") -- remove file extention
        local opts = {
          window = win, -- THIS IS THE NEW PART
          relative = true,
          restore_text = true,
          on_pane_restore = resurrect.tab_state.default_on_pane_restore,
        }
        if type == "workspace" then
          local state = resurrect.load_state(id, "workspace")
          resurrect.workspace_state.restore_workspace(state, opts)
        elseif type == "window" then
          local state = resurrect.load_state(id, "window")
          resurrect.window_state.restore_window(pane:window(), state, opts)
        elseif type == "tab" then
          local state = resurrect.load_state(id, "tab")
          resurrect.tab_state.restore_tab(pane:tab(), state, opts)
        end
      end)
    end),
  },
 ```
 
As for "replacing" your current windows, it is tricky because from a plugin authors perspective I don't want to be intrusive and close tabs/panes which you as a user did not intent to close, losing important work in the progress. 
However you can do this yourself by using:
[window:tabs](https://wezfurlong.org/wezterm/config/lua/mux-window/tabs.html) to get the tabs of the window.
Spawn a new tab with [Window:spawn_tab](https://wezfurlong.org/wezterm/config/lua/mux-window/spawn_tab.html).
Close all tabs from the list with something like: [CloseCurrentTab](https://wezfurlong.org/wezterm/config/lua/keyassignment/CloseCurrentTab.html?h=close).
And then resurrecting the state with the window.

**Comment by weierophinney** [comment]
First, thanks for the quick response!

Adding the `window = win` property to the opts now results in a no-op when attempting to load a workspace, and the workspace I attempted to load does not show up as a workspace in the workspace list.

Removing it, the workspace loads fine, but still spawns a new window.

(Also checked, and I'm using latest from the main branch.)

**Comment by MLFlexer** [comment]
Sorry, the window that is passed into the `opts` must be a `MuxWindow`, but what is passed in is a `GuiWindow`. As such the code should be this instead:
```lua
 {
    key = "r",
    mods = "ALT",
    action = wezterm.action_callback(function(win, pane)
      resurrect.fuzzy_load(win, pane, function(id, label)
        local type = string.match(id, "^([^/]+)") -- match before '/'
        id = string.match(id, "([^/]+)$") -- match after '/'
        id = string.match(id, "(.+)%..+$") -- remove file extention
        local opts = {
          window = win:mux_window(), -- THIS IS THE NEW PART
          relative = true,
          restore_text = true,
          on_pane_restore = resurrect.tab_state.default_on_pane_restore,
        }
        if type == "workspace" then
          local state = resurrect.load_state(id, "workspace")
          resurrect.workspace_state.restore_workspace(state, opts)
        elseif type == "window" then
          local state = resurrect.load_state(id, "window")
          resurrect.window_state.restore_window(pane:window(), state, opts)
        elseif type == "tab" then
          local state = resurrect.load_state(id, "tab")
          resurrect.tab_state.restore_tab(pane:tab(), state, opts)
        end
      end)
    end),
  },
  ```

**Comment by weierophinney** [comment]
Wonderful! That works!

I've identified an improvement now as a result: when you restore, the workspace name is not updated to reflect the workspace you're restoring from. I can see that you might not want to do that (example: you may want to "fork" the workspace so you can work in parallel, but with the same starting point). However, if you _did_ want to restore it, I don't see a way to do so currently. `workspace_state::restore_workspace` doesn't do anything with `workspace_state.workspace`, the `resurrect.workspace_state.restore_workspace.finished` event is not provided any arguments, so I cannot tie into it via an event hook, either.

I'm happy to work on a patch for this; is it something you'd want in the project?

**Comment by MLFlexer** [comment]
> Wonderful! That works!
> 
> I've identified an improvement now as a result: when you restore, the workspace name is not updated to reflect the workspace you're restoring from. I can see that you might not want to do that (example: you may want to "fork" the workspace so you can work in parallel, but with the same starting point). However, if you _did_ want to restore it, I don't see a way to do so currently. `workspace_state::restore_workspace` doesn't do anything with `workspace_state.workspace`, the `resurrect.workspace_state.restore_workspace.finished` event is not provided any arguments, so I cannot tie into it via an event hook, either.

Is it correctly understood that you want to replace the current workspace completely with another workspace which has been resurrected? If so, then I would probably go about this the other way around. 
I would start by creating a workspace, and then based on the name of the newly created workspace, I would then resurrect the state.

> I'm happy to work on a patch for this; is it something you'd want in the project?
If the comment above about first creating and then resurrecting the workspace does not fit your needs, then others might share the same needs.
It would be greatly appreciated if you could provide a path! Otherwise then I'm happy helping with implementing this. Do you just want extra arguments to the event, or does this feature need more than this?

Either way, if you see a shortcomming with the current implementations, then I would appreciate your feedback 😄

**Comment by weierophinney** [comment]
> If so, then I would probably go about this the other way around.

I did some thinking about this, and decided I'd just change my workflow slightly. I'm now renaming the workspace either before or after resurrect, as that also gives me the opportunity to use an existing session as a "template" for another session if needed, while still being able to get back to where I as previously.

Thanks for all your help!
